[[GETTINGCOMFORTABLE]]
Getting Comfortable with Erlang
-------------------------------

NOTE: You can learn more about working with +erl+ in Chapter 2 of _Erlang Programming_, Chapters 2 and 6 of _Programming Erlang_, Section 2.1 of _Erlang and OTP in Action_, and Chapter 1 of _Learn You Some Erlang For Great Good!_.

[[CH01-ET01]]
Étude 1-1: Experimenting with Errors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The first chapter of
http://shop.oreilly.com/product/0636920025818.do[Introducing Erlang]
encourages you to play around with the interactive +erl+ system.
In this étude, keep using +erl+, but purposely make errors.

Try leaving out parentheses in arithmetic expressions. Try putting
numbers next to each other without an operator between them.
Try adding +"adam"+ to +12+. Make up variable names that you are sure
Erlang wouldn't ever accept.

That way, you'll get a feel for the sort of error messages
Erlang produces and not be as baffled when you get errors that
you aren't expecting.


