[[preface]]
== Etudes for Erlang

Welcome to _Etudes for Erlang_.  In this book, you will find descriptions of programs that you can compose (write) in Erlang.The programs will usually be short, and each one has been designed to provide practice material for a particular Erlang programming concept. These programs have not been designed to be of considerable difficulty, though they may ask you to stretch a bit beyond the immediate material and examples that you find in the book http://shop.oreilly.com/product/0636920025818.do[Introducing Erlang].

This book is open source, so if you'd like to contribute, make a correction, or otherwise participate in the project, check out https://github.com/oreillymedia/etudes-for-erlang[oreillymedia/etudes-for-erlang] on GitHub for details. If we accept your work, we'll add you to the contributors page.

=== How to Contribute

If you are interested in contributing to the project, check out https://github.com/oreillymedia/etudes-for-erlang/blob/master/HOW_TO_CONTRIBUTE.asciidoc[How To Contribute].  The tl;dr is:

* Conversational tone.  Be professional, not professorial.
* 400 - 500 words
* Include your name and a short biography at the end of your contribution
* You agree to put your contribution under the link::http://creativecommons.org/licenses/by/3.0/us/[Creative Commons Attribution 3.0 license]
* Your submission may not be accepted
* Fork this project repo to your new account
* Submit your contribution
** Work in the master branch (we know this isn't ideal, but there it is)
** Write in http://powerman.name/doc/asciidoc[AsciiDoc] 
** Include your name and bio
* Submit a pull request when your contribution is as close to perfect as you can get it
* Engage with us in the discussion
